### ISSUE TITLE
Nathan's to-do & have done

### ISSUE THREAD

**Issue by Central120** [Central120/uniwork#3]
# Nathan's to-do & have done

### Gallery
- [x] Create the main-frame design of the gallery index
- [x] Position the design to provide optimal optimization for both mobile and desktop devices
- [x] Create a database link between the gallery database and the gallery index to pull gallery items from
- [x] Ensure that all important information has been provided onto the gallery image submissions (the user who uploaded, when it was uploaded, report information)
- [x] Create an upload feature to allow logged in users to share images of their desire, pets, products or anything related to the site
- [x] Create a report feature that allows users and/or guests to report an image depending whether it goes against the site's code of conduct or terms of use.

### Gallery - Admin Panel
- [x] Create a page that lists all the image information in a table (ensure that the image is only shown externally via a href link so it doesn't take room up on the page and look messy)
- [x] In the same page, add the option to manage a specific image submission
- [x] Allow the admin to Delete the Image
- [x] Allow the admin to mark the image for approval (hide and mark image as approval)
- [x] Allow the admin to view the image from the admin panel

### Gallery - Report Admin Panel
- [x] Create a page that lists all the active and closed reports information inside a table
- [x] Allow the admin to Close the report with no action taken
- [x] Allow the admin to Close the report and delete the image
- [x] Allow the admin to also view the image via the admin report panel

### Accounts - Admin Panel
- [x] Create a table that lists all the account information that can be shown to admins (Account ID, Username, Security Questions (without answers) and the admin status (user or admin))
